language: java
jdk:
  - openjdk8

script: ./mvnw clean install

jobs:
  include:
    - stage: Test
      script: ./mvnw clean test

notification:
  email: info@techprimers.com

deploy:
  provider: heroku
  api_key:
    - secure: $SECURE_KEY
  app: $APP